---
title: "Metabolome Analysis"
author: "Rob Markowitz"
date: "1/25/2020"
output: html_document
fig_width: 5


#KO/ARG Analysis 
library(tidyverse)
library(vegan)
library(ggtext)
library(ggpubr)
library(gridExtra)
library(cowplot)
set.seed(999)

#Collect Data 
dir <- "/Users/goblinking/Projects/ko_args/"
data <- read.table(paste(dir,"ko2.tsv",sep=""), sep='\t',header=T)
meta <- read_csv(paste(dir,"year2_meta.csv",sep=""))
distance <- "jaccard"
#Filter data

#####Merge metadata and abundance data 
run <- left_join(meta,data) %>% 
  filter(source == "oral" & UNMAPPED != "NA")

met <- run[,1:9] 
dat <- as.matrix(run[,10:length(run)])
var <- "Ethnicity"
adonis2(dat~ var, data = met, permutations = 4999, by = "margin", method = distance,na.rm = T)

#FECAL
run<- left_join(meta,data) %>% 
  filter(source == "fecal" & UNMAPPED != "NA")
met <- run[,1:9] 
dat <- as.matrix(run[,10:length(run)])
adonis2(dat~ var, data = met, permutations = 4999, by = "margin", method = distance,na.rm = T)

#nMDS
nmds<- metaMDS(dat, k=2, trymax=499, dist = distance)
m3<-scores(nmds)
df<-cbind(m3,met)

#Set Factors 
df$Ethnicity <- factor(df$Ethnicity, levels=c("Black","White"))
df$`Study period` <- factor(df$`Study period`, levels=c("Before","During","After"))
df$`Study period` <- factor(df$`Study period`, levels=c("Before","After"))
df$SampleID <- as.factor(df$SampleID)

#Plots####

brayfs <- ggplot(df, aes(x = NMDS1, y = NMDS2, 
                         color = `Study period`)) +
  geom_point(size=3) + scale_color_manual(
    values = c("Before"="#238b45","During" = "#d94801", "After"="#2171b5")) + scale_fill_manual(
      values = c("Before"="#238b45","During" = "#d94801", "After"="#2171b5")) +
  theme(panel.background = element_rect(fill = 'White', colour = 'Black'), 
        legend.key=element_blank()) + 
  theme(axis.title.x=element_text(size=rel(2)), 
        axis.title.y=element_text(size=rel(2)),
        plot.title = element_text(size=rel(3)),
        legend.title = element_text(size=rel(2)),
        legend.text = element_text(size = rel(1.8))) +
  stat_ellipse(data = df, aes(x = NMDS1, y = NMDS2, 
                              fill = `Study period`), 
               alpha = 0.2, size = 0.8, geom = "polygon",
               linetype = 2,
               type = "t", level = 0.95) + 
  ggtitle("KO - Bray-Curtis - Fecal")  +
  annotate(geom = "richtext", fill = NA, label.color = NA,
           label = "<i>p</i> = 0.993, r<sup>2</sup> = 0.6% (Both)<br><i>p</i> = 0.999, r<sup>2</sup> = 0.7% (Black)<br><i>p</i> = 0.903, r<sup>2</sup> = 1.7% (White)<br>", 
           x = Inf, y = Inf, size = 4,
           hjust = 1.1, vjust = 1.1)  +
  annotate(geom = "richtext", fill = NA, label.color = NA,
           label = "Stress = 1.30",
           x = Inf, y = -Inf, size = 4,
           hjust = 1.1, vjust = 0)

brayos <- ggplot(df, aes(x = NMDS1, y = NMDS2, 
                                         color = `Study period`)) +
  geom_point(size=3) + scale_color_manual(
    values = c("Before"="#238b45","After"="#2171b5")) + 
  scale_fill_manual(values = c("Before"="#238b45","After"="#2171b5")) +
  theme(panel.background = element_rect(fill = 'White', colour = 'Black'), 
        legend.key=element_blank()) + 
  theme(axis.title.x=element_text(size=rel(2)), 
        axis.title.y=element_text(size=rel(2)),
        plot.title = element_text(size=rel(3)),
        legend.title = element_text(size=rel(2)),
        legend.text = element_text(size = rel(1.8))) +
  stat_ellipse(data = df, aes(x = NMDS1, y = NMDS2, 
                                              fill = `Study period`), 
               alpha = 0.2, size = 0.8, geom = "polygon",
               linetype = 2,
               type = "t", level = 0.95) + 
  ggtitle("KO - Bray-Curtis - Oral")  +
  annotate(geom = "richtext", fill = NA, label.color = NA,
           label = "<i>p</i> = 0.765, r<sup>2</sup> = 1.7% (Both)<br><i>p</i> = 0.567, r<sup>2</sup> = 3.9% (Black)<br><i>p</i> = 0.566, r<sup>2</sup> = 5.7% (White)<br>", 
           x = Inf, y = Inf, size = 4,
           hjust = 1.1, vjust = 1.1)  +
  annotate(geom = "richtext", fill = NA, label.color = NA,
           label = "Stress = 0.139",
           x = Inf, y = -Inf, size = 4,
           hjust = 1.1, vjust = 0)
brayos

#Create figures 
tiff(file = "nmds_KO_StudyPeriod.tif", res = 150, width = 18, 
     height = 7, units = "in")
legend1 = get_legend(brayfs + theme(legend.box.margin = margin(0, 0, 0, 12)))
col1 = plot_grid(brayfs + theme(legend.position = "none"),
                 nrow = 1, ncol = 1, labels = c('A'), 
                 label_size = 20)
col2 = plot_grid(brayos + theme(legend.position = "none"),
                 nrow = 1, ncol = 1, labels = c('B'), 
                 label_size = 20) 
plot = plot_grid(col1, col2, legend1, nrow = 1, ncol = 3, 
                 rel_widths = c(1.5, 1.5, 0.75), align = "h", axis = "t")
plot
dev.off()